### PR TITLE
Resources: User Stories, Community, and Blog

### PR DESCRIPTION
**Pull request by yuhan**
The goal of this PR is to promote the visibility of user stories and community meetings, and therefore communicate the maturity and drive community engagement.

It built three things:

1) Standalone `/user-stories` page:
- tagged existing blog posts to categorize posts
- created a standalone page for showing user stories (it's derived from the blog posts. the idea is to promote user stories so it's easier to find)
- made a few cover images for user story posts so the page looks nicer visually

2) Standalone `/community` page: 
- dded `metadata.json` file that collects community meeting info like youtube links
- created a standalone page for showing 1) upcoming events 2) past events which link to youtube videos
- added CTAs: 1) "join us on slack" with numbers 2) "contact us" for presenting at community meetings
- collected external talks and podcasts

Next steps:
1. Link #65 to the User Stories page
2. Collect and show more user testimonials (or community engagement in general)

### CODE REVIEW

**Comment by catherinewu** [comment]
wow this looks great! some small notes -- on the user stories page, what do you think of including user presentations from the community meetings and other talks and blog posts that users have written about us? also, would love to have a prominent button on the dagster.io landing page that links to this (maybe I should update https://github.com/dagster-io/dagster-website/pull/65 to use tailwind and include a click through to the user stories page instead of the third quote)

**Comment by yuhan** [comment]
@catherinewu 
> on the user stories page, what do you think of including user presentations from the community meetings and other talks and blog posts that users have written about us? 

yes! that's the final goal i think. so i think we'd 1) collect all "resources" (both from us and from users) 2) categorize them and show them in a convincing and helpful way. will do it in a followup - mostly would like to play around with the layout/flow a bit more.

> a prominent button on the dagster.io landing page that links to this

that's exactly my next step! i was thinking of having multiple entry points for this page (the goal here i think is to promote the user stories/testimonials so multiple entry points could be good): 1) from the top menu "resources > user-stories" 2) from landing page, i.e. exactly what you suggested

**Comment by yuhan** [comment]
@catherinewu @mgasner would love to have you take another pass 

I updated this PR with the external resources section (e.g. talks, podcasts, blogs) on the [Community](https://dagster-website-cqnde2uux-elementl.vercel.app/resources/community) page - pulled external talks and podcasts we collected in https://dagster.phacility.com/D6301 (as of Jan 2021). going forward, we can add links and descriptions to the json file so they would show up in our website :)

**Review by sryza — APPROVED** [review]
lgtm! I think it would be helpful if we could somehow combine the good eggs posts underneath a single heading, but I don't know if that's a blocker

**Comment by yuhan** [comment]
re: combing posts from the same org, yup i will explore options as a followup!

**Pull request merged**
